version: "3"
services:
  db:
    image: postgres:latest
    environment:      
      - SECRET_KEY=averyhardstring
      - POSTGRES_USER=testusr     
      - POSTGRES_PASSWORD=password      
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
  flaskapp:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "5000:5000"
    depends_on:
      - "db"


  